Add SigV4 middleware
grafana/grafana-aws-sdk pull request #4
Opened 2020-12-11 15:53 UTC by wbrowne

Fixes https://github.com/grafana/grafana/issues/29738

Usage looks like:

```go
return &SigV4Middleware{
		Config: &Config{
			Service:        "es",
			AccessKey:      "blah",
			SecretKey:      "blah",
			Region:         "eu-central-1",
			AssumeRoleARN:  "", // optional
			AuthType:       "default",
			ExternalID:     "", // optional
			Profile:        "default",
		},
		Next: nil, // optional subsequent middleware 
	}
```

2021-01-11 08:57 UTC, wbrowne commented
Will need to keep in sync with these latest changes here https://github.com/grafana/grafana/pull/30115

2021-01-12 09:28 UTC, marefr requested changes
Some minor things, see comments. Comments around sharing the credentials creation/models in this lib is something to consider/discuss later.

2021-01-12 09:28 UTC, marefr commented on pkg/sigv4/sigv4.go
> +type Config struct {
Nit. Don't need to handle in this PR, but moving forward think this is very similar to awsds auth and would be nice if the actual credentials creation code was shared, but not sure that's possible?

2021-01-12 11:15 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +type AuthType string
Yep - agreed!

2021-01-12 12:40 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +type Config struct {
I think it should be. Will confer with @ryantxu as a form of refactoring afterwards

2021-01-12 14:17 UTC, marefr approved these changes
LGTM, but added a comment regarding the optional middleware

2021-01-12 14:17 UTC, marefr commented on pkg/sigv4/sigv4.go
> +		}
Nit. Would rather require the client to provide `next` to make it more explicit that the middleware wont function without `next` provided. But that would either require an error to be returned from `New` or potentially a `panic` but that's ugly.

2021-01-12 15:17 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +		}
Yeah, that's a potential scenario. I think let's keep it as is and can refactor that out (or just add another alternative `New` func) later if necessary

2021-01-12 15:17 UTC, merged