SigV4: Guarantee consistency of signed headers
grafana/grafana-aws-sdk pull request #48
Opened 2022-02-03 13:32 UTC by wbrowne

Changes:

- Reconstructs signer only when necessary
- Only signs minimal amount of headers (`Host` and `X-Amz-Date`) - using the approach followed [here](https://github.com/awslabs/aws-sigv4-proxy) as a reference
- Fixes badly formatted log lines
- Added support for debugging bad signature scenarios by requiring a `Logger` implementation

2022-02-03 15:03 UTC, andresmgot reviewed
Mostly looks good to me but I feel I don't have full context so letting @marefr to do a final review. BTW, should this be associated to some issue?

2022-02-03 15:47 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +func New(cfg *Config, next http.RoundTripper, logger Logger) (http.RoundTripper, error) {
Yeah it's not great - I just amended to introduce a second signature so as not to have a breaking change. Alternatively it might look better with a variadic `opts` argument of some sort perhaps. 

I'm not too keen on adjusting the Config struct as that's dedicated for AWS specific config for authentication, so doesn't feel at home there IMO.

2022-02-03 16:49 UTC, marefr requested changes
In general looks good, but added some comments.

2022-02-03 16:49 UTC, marefr commented on pkg/sigv4/sigv4.go
> +	h.Write([]byte(fmt.Sprintf("%v", c)))
Lint error, need to handle error

2022-02-03 16:49 UTC, marefr commented on pkg/awsds/settings.go
> +func ToAuthType(authType string) (AuthType, error) {
Is this a breaking change? And/or only used internally?

2022-02-03 16:49 UTC, marefr commented on pkg/sigv4/sigv4.go
> +type Logger interface {
Want to use the logger interface from SDK, https://github.com/grafana/grafana-plugin-sdk-go/blob/a62a98d0ea262e968f84970dc9fce2ae4969da34/backend/log/log.go#L20-L26, instead? 

The request specific logger can be implemented on top I suppose.

Update: Ohh I see you provide this to aws SDK now so understand it requires a certain interface. The verbose part as well, probably needs some special handling as well so that we don't expose sensible information in logs.

2022-02-03 16:49 UTC, marefr commented on pkg/sigv4/sigv4.go
> +	if err := validateConfig(cfg); err != nil {
Maybe should check that logger is not nil?

2022-02-03 16:49 UTC, marefr commented on pkg/sigv4/sigv4.go
> +		sync.RWMutex
Might consider using https://pkg.go.dev/sync#Map

> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

2022-02-03 17:20 UTC, wbrowne commented on pkg/awsds/settings.go
> +func ToAuthType(authType string) (AuthType, error) {
Yeah - currently only used internally. Was specifically introduced as a helper for SigV4 so it looks like it's the only thing using it AFAICT

2022-02-04 08:59 UTC, andresmgot commented on pkg/sigv4/sigv4.go
> +}
will the logger really change in different calls? it seems to me that this logger parameter is only defined to use a different logger in the tests. If that's the case, I would define a default logger as a package variable so the caller does not need to use this new function and doesn't have to bother to learn about how this logger works internally.

2022-02-04 09:31 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +}
The main idea with the logger is to provide us an easier way to debug SigV4 issues as we don't have anything in place right now. With that, we need some form of  control that so that we can only enable that when appropriate - as for example we don't want to always do HTTP request dumps. Given that it's an interface, the caller can decide what to do with it, based on however logging is done there.

The existing logger from the plugin SDK doesn't provide anything useful unfortunately. Furthermore, this new interface also fits the shape of the interface expected by the AWS logger IE
```golang
var signerOpts = func(s *v4.Signer) {
	if logger.VerboseMode() {
		s.Logger = logger
		s.Debug = aws.LogDebugWithSigning
	}
}
```

Thinking about it differently, maybe instead we could have:

```golang
func New(cfg *Config, next http.RoundTripper, opts ...SigV4Options) (http.RoundTripper, error) {
	return newRoundTripper(cfg, next, opts.debugEnabled)
}

```

`debugEnabled` can be our control to enable logging within the AWS SDK (using aws.LogDebugWithSigning) and to also decide whether or not to dump the requests. And we can use plugin SDK logger for our logging needs.

🤔  WDYT?

2022-02-04 12:43 UTC, andresmgot commented on pkg/sigv4/sigv4.go
> +}
got it. So my question now is, would the logger level differ between the default logger and this logger? (for example setting the default log level to "info" and this one to "debug"). If the answer is "no, both will be the same", then, is there a better way to get that log level without changing the interface of this method? (something like `backend.Logger.Level()` or alike). If the answer is no again then I agree with your proposed interface change. Thanks for checking this!

2022-02-04 12:53 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +}
Technically they could be different, but I think they should not differ. 

Ah! Great tip - that just reminded me that this [exact thing was added to the plugin SDK](https://github.com/grafana/grafana-plugin-sdk-go/pull/435). Let me give that a shot

2022-02-04 13:20 UTC, marefr commented on pkg/awsds/settings.go
> +func ToAuthType(authType string) (AuthType, error) {
Okay :+1:

2022-02-04 13:23 UTC, marefr commented on pkg/sigv4/sigv4.go
> +}
But level is always debug by default for backend plugins so I think a specific verbose config for sigv4 is still needed. Talked about it in my update here https://github.com/grafana/grafana-aws-sdk/pull/48#discussion_r798752336

2022-02-04 13:30 UTC, marefr reviewed
Great, but some minor things left.

2022-02-04 13:30 UTC, marefr commented on pkg/sigv4/sigv4.go
> +		return ""
Nit. Not sure in what way this could fail, but feels like the error should be returned rather than swallowed.

2022-02-04 13:30 UTC, marefr commented on pkg/sigv4/sigv4.go
> +		if plog.Level() == log.Debug {
Already left a comment regarding this. Default level is debug for backend plugins so this is probably not what we want given the sensitive information that might be logged. Verbose config was more suitable I think.

2022-02-04 13:31 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +		if plog.Level() == log.Debug {
Maybe the `trace` level in that case?

2022-02-04 13:34 UTC, marefr commented on pkg/sigv4/sigv4.go
> +		if plog.Level() == log.Debug {
Yeah might work

2022-02-04 13:57 UTC, marefr commented on pkg/sigv4/sigv4.go
> +		if plog.Level() == log.Debug {
Only thing to keep in mind is that Grafana will log traces with debug level

2022-02-04 13:58 UTC, wbrowne commented on pkg/sigv4/sigv4.go
> +		if plog.Level() == log.Debug {
Yeah.. it's a weird side effect. Okay let me look at the passing opts instead 🕺

2022-02-04 14:54 UTC, andresmgot approved these changes
thanks for checking the changes!

2022-02-04 14:54 UTC, andresmgot commented on pkg/sigv4/sigv4.go
> +	a.logger.Info("AWS debug log", args...)
this is new, right? do you want that to appear in all the logs?

2022-02-08 09:23 UTC, marefr approved these changes
LGTM, but needs to fix failing test

2022-02-08 10:16 UTC, merged